### ISSUE TITLE
What is the `dotnet` cli tool?

### ISSUE THREAD

**Issue by canadaduane** [AngelMunoz/perla-templates#1]
I see `dotnet` used as a cli tool to install things and make a local server of some kind. Do I need Microsoft .NET to use Perla?

Context: I'm coming from a nodejs / webdev background but haven't heard of `dotnet` and don't know why I would use it to try Perla.

**Comment by AngelMunoz** [comment]
Hello!
The templates were made with .NET in mind since I am building the tool with it BUT BUT that's just an extra commodity for .NET users

if you come from other backgrounds, don't worry check the instructions here

https://perla-docs.web.app/#/content/install

basically you need to download one of the pre-releases, unzip the file and put it on your path no .NET needed or anything else

you can delete the dotnet related directories afterwards,

once you put Perla on the path you can run it like the examples say

`perla serve` on the root of the example you want to try

If you have doubts or problems let me know

**Comment by canadaduane** [comment]
Ok, thanks for the explanation! Still poking around, but I'll write again if need be :)

**Comment by AngelMunoz** [comment]
I will close this one now, feel free to re-open if necessary feedback is welcome on the main repository https://github.com/AngelMunoz/Perla/issues :)
